config/routes.rb
PopHealth::Application.routes.draw do

  apipie

  devise_for :users, :controllers => {:registrations => "registrations"}

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  get "admin/jobs"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  delete "admin/remove_jobs"
  post 'api/measures/finalize'
  post 'api/measures/update_metadata'
  get "logs/index"
  post 'home/set_reporting_period'
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default"
  get 'home/check_authorization'
  delete "practices/remove_patients"
  delete "practices/remove_providers"
  delete "/api/admin/patients/deletePatientsFromPractice"

  put 'admin/patient', :to => 'admin/patients#upload_single_patient'

  root :to => 'home#index'

  resources :practices

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    get :measure_baseline

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams

  namespace :api do
    get 'reports/*qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
    get 'reports/*cat1.zip', :to =>'reports#cat1_zip', :format => :zip
    get 'reports/cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/patients', :to => 'reports#patients'
    get 'reports/measures_spreadsheet', :to =>'reports#measures_spreadsheet'
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/team_report', :to => 'reports#team_report'

    get 'value_sets/:oid', :to => 'value_sets#show', :oid => /([^\/])+?/, :format => :json

    resources :practices do
      collection do
        get :search
      end
    end
    
    resources :measure_baselines
    resources :practices
    resources :teams
    namespace :admin do
      resource :caches do
        collection do
          get :count
          get :spinner
          get 'static_measure/:id', :to => :static_measure
        end
      end
      resource :patients do
        collection do
          get :count
        end
      end
      resource :providers do
        collection do
          get :count
        end
      end
      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
    resources :providers do
      collection do
        get :search
      end
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end
    end
    resources :patients do
      member do
        get :results
      end
    end

    resources :measures

    resources :queries do
       member do
        get :patients
        get :patient_results
        put :recalculate
        post :filter
        post :clearfilters
       end
    end
  end

end

app/views/admin/jobs.html.erb
<div id="pageContent" style="padding:20px;">
  <h3>Background Jobs</h3>

  <table width="500px">
    <tr>
      <td colspan="2">Total jobs:</td>
      <td><%= @job_count %> jobs</td>
      <td>
        <%= button_to "Delete All Jobs", "/admin/remove_jobs", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>Measure Calculation:</td>
      <td><%= @calculation_job_count%> jobs</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>Patient Import:</td>
      <td><%= @patient_job_count%> jobs</td>
      <td>&nbsp;</td>
    </tr>
  </table>
</div> <!-- pageContent -->

app/views/admin/patients.html.erb
<div id="pageContent" style="padding:20px;">
<h3>Patients</h3>

  <table>

    <tr><td>patients loaded: </td>
      <td>
        <span id="patient_count"><%= @patient_count %></span> patients
        <%= image_tag "load.png", :id => "loadingPatient", 'class' => 'loader'%>
      </td>
      <td>
        <%= button_to "Delete Patients", "/admin/remove_patients", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
      <td >
        
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>

    <tr><td>cache counts: </td>
      <td>
        query cache: <%= @query_cache_count%> <br>
        patient cache: <%= @patient_cache_count%>
      </td>
      <td>
        <%= button_to "Delete Caches", "/admin/remove_caches", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>

    <tr><td>providers loaded: </td>
      <td>
        <%= @provider_count %> providers

      </td>
      <td>
        <%= button_to "Delete Providers", "/admin/remove_providers", 'method' => 'delete', 'class' => 'btn btn-danger'%>
      </td>
    </tr>
    
    <% if !APP_CONFIG['use_opml_structure'] %>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
      <td> Practices </td>
      <td> <%= @practice_count %> practices </td>
      <td> <%= link_to "Edit Practices", practices_path, :class => "btn btn-large btn-success"%> </td>
    </tr>
    <% end %>

    <tr><td colspan="2">&nbsp;</td></tr>
    <%= form_tag("/admin/upload_patients", :method => "put", :multipart=>true, :class=>"file-upload") do %>
    <% if !APP_CONFIG['use_opml_structure'] %>
    <tr>
      <td> <%= label_tag "Choose practice" %> </td>
      <td> <%= select_tag "practice", options_for_select(@practices), include_blank: true, style: 'width:200px' %></td>					
    </tr>
    <% end %>
    <tr><td>Upload patient zip file: </td>
      <td>
        <%= file_field_tag(:file)%>
      </td>
      <td><%= submit_tag("Upload", 'class' => "btn btn-success") %></td>
    </tr>
    <% end %>

    <% if APP_CONFIG['use_opml_structure'] %>
      <tr><td colspan="2">&nbsp;</td></tr>
      <%= form_tag("/admin/upload_providers", :method => "put", :multipart=>true, :class=>"file-upload") do %>
      <tr><td>Upload provider opml file: </td>
        <td>
          <%= file_field_tag(:file)%>
        </td>
        <td><%= submit_tag("Upload", 'class' => "btn btn-success") %></td>
      </tr>
      <% end %>
    <% end %>

  </table>

</div> <!-- pageContent -->
<script>
  $(document).ready(function() {
    $(".file-upload").submit(function(e) {
      if (this.practice.value === "") {
        alert("Please choose a practice.");
        e.preventDefault();
      }
      else if (this.file.value === "" ) {
        alert("Please provide a file.");
        this.file.focus();
        e.preventDefault();
      }
      else {
        var confs = "Are you sure you want to upload patients for the chosen practice?";
        if (confirm(confs) == false){
          e.preventDefault();
        }
      }
    });
    (function poll(){
       setTimeout(function(){
        $.getJSON( "<%= count_api_admin_patients_path %>", function(data){
          $('#patient_count').html(data.patient_count);
          //Setup the next poll recursively
          poll();
        });
      }, 5000);
    })();

    (function loader(){
       setTimeout(function(){
        $.getJSON( "<%= spinner_api_admin_caches_path %>", function(data){
          console.log(data);
          if(data.spinner_stat >0){
            console.log("in if");
            $('#loadingPatient').addClass('loaderspin');
          }else{
            $('#loadingPatient').removeClass('loaderspin');
          }
          //$('#patient_count').html(data.patient_count);
          //Setup the next poll recursively
          loader();
        });
      }, 5000);
    })();
  });
</script>

app/views/admin/user_profile.html.erb
<script type='text/javascript'>
  $(document).ready(function() {
    $('.practice_select').change( function(){
      var userId = $(this).data("user");
      var practice = $(this).val();
      var confs = "Change user's assigned practice?";
      
      if ( confirm(confs) == true ){
        $.post('set_user_practice', {'user': userId, 'practice': practice}, function(d){
        });
      };     
    });
    
    $('.practice_provider_select').change( function() {
      var userId = $(this).data("user");
      var provider = $(this).val();
      var confs = "Change user's assigned provider?";   
      if ( confirm(confs) == true ){
        $.post('set_user_practice_provider', {'user': userId, 'provider': provider}, function(d){
        }); 
      };
    });
    
  });
</script>
<div class='main' >
  <h1>User Profile:  <strong><%= @user.full_name%> </strong></h1>

  <table class="table table-hover user-profile">
	<% unless APP_CONFIG['use_opml_structure'] %>
	  <tr>
		  <% if @user.staff_role %>
		    <td> <h4> Practice: </h4> </td>
		    <td> <h4> <%= select_tag "practice", options_for_select(@practices, @user.practice_id), prompt: 'None', data: {user: @user.id.to_s}, class: "practice_select" %> </h4> </td>
		  <% elsif @user.provider_id && Provider.valid_npi?(@user.npi)%>
		    <td> <h4> Provider: </h4> </td>
		    <td> <h4>         
          <%= select_tag "practice_provider_select", options_for_select(@practice_pvs, @user.provider_id), prompt: 'None', data: {user: @user.id.to_s}, class: 'practice_provider_select'%> 
		    </h4> </td>
		  <% end %>
	  <tr>
    <% end %>

	  <tr>
		  <td class='up-col'> Username: </td>
		  <td> <%= @user.username %> </td>
	  <tr>

	  <tr>
		  <td class='up-col'> Email: </td>
		  <td> <%= @user.email %> </td>
	  <tr>

	  <tr>
		  <td class='up-col'> Organization: </td>
		  <td> <%= @user.company %> </td>
	  <tr>

	  <tr>
		  <td class='up-col'> Organization URL: </td>
		  <td> <%= @user.company_url %> </td>
	  <tr>

	  <tr>
		  <td class='up-col'> Registry Name: </td>
		  <td> <%= @user.registry_name %> </td>
	  <tr>

	  <tr>
		  <td class='up-col'> Registry ID: </td>
		  <td> <%= @user.registry_id %> </td>
	  <tr>

	  <tr>
		  <td class='up-col'> National Provider Id: </td>
		  <td> <%= @user.npi %> </td>
	  <tr>

	  <tr>
		  <td class='up-col'> Tax Identifier: </td>
		  <td> <%= @user.tin %> </td>
	  <tr>
  </table>		

  <%= link_to "Back to Users", "/admin/users", :class=>"btn btn-success" %>
</div>

app/views/admin/users.html.erb
<script type="text/javascript">
  var popHealth = popHealth || {};

  popHealth.promoteUser = function() {
    var username = $(this).data("username");
    var role = $(this).data("role");
    var parentTd = $(this).parent();
    $.post('<%= admin_promote_path %>', {'username': username, 'role': role}, function(data) {
      parentTd.html(data);
      parentTd.find('.demote').click(popHealth.demoteUser);
    });
    return false;
  };

  popHealth.demoteUser = function() {
    var username = $(this).data("username");
    var role = $(this).data("role");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to remove admin rights from the currently logged in user' 
      +', this will cause you to immediately lose access to all admin functionality including this page.  ' 
      +'You will need to use another admin account to restore admin rights.  Are you sure you want to continue?');
      if (!response) return;
    }

    $.post('<%= admin_demote_path %>', {'username': username, 'role': role}, function(data) {
      parentTd.html(data);
      parentTd.find('.promote').click(popHealth.promoteUser);
    });
    return false;
  };

  popHealth.approveUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    $.post('<%= admin_approve_path %>', {'username': username}, function(data) {
      parentTd.html(data);
    });
  };

  popHealth.disableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to disable the currently logged in user' 
      +', this will cause you to immediately lose access and be logged out.  Are you sure you want to continue?');
      if (!response) return;
    }

    popHealth.disableEnableUser(1, username, parentTd)
  };
  popHealth.enableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    popHealth.disableEnableUser(0, username, parentTd)
  };
  popHealth.disableEnableUser = function(disabled, username, parentTd) {
    $.post('<%= admin_disable_path %>', {'username': username, 'disabled': disabled}, function(data) {
      parentTd.html(data);
      if (disabled == 1) parentTd.find('.disable').click(popHealth.enableUser);
      else parentTd.find('.enable').click(popHealth.disableUser);
    });
  };
  popHealth.changeNpi = function() {
    var username = $(this).data("username");
    var npi = $(this).val();
    $.post('<%= admin_update_npi_path %>', {'username': username, 'npi': npi}, function(data) {
    });
    
  };
  
  popHealth.changePractice = function() {
    var userId = $(this).data("user");
    var practice = $(this).val();
    var confs = "Change user's assigned practice?";   
    if ( confirm(confs) == true ){
      $.post('set_user_practice', {'user': userId, 'practice': practice}, function(d){
      }); 
    };
  };
  
  popHealth.changePracticeProvider = function() {
    var userId = $(this).data("user");
    var provider = $(this).val();
    var confs = "Change user's assigned provider?";   
    if ( confirm(confs) == true ){
      $.post('set_user_practice_provider', {'user': userId, 'provider': provider}, function(d){
      }); 
    };
  };

  $(document).ready(function() {
    $('.promote').click(popHealth.promoteUser);
    $('.demote').click(popHealth.demoteUser);
    $('.approve').click(popHealth.approveUser);
    $('.enable').click(popHealth.disableUser);
    $('.disable').click(popHealth.enableUser);
    $('.npi_select').change(popHealth.changeNpi);
    $('.practice_select').change(popHealth.changePractice);
    $('.practice_provider_select').change(popHealth.changePracticeProvider);
  });
</script>

<div id="pageContent">
<%= if !APP_CONFIG['use_opml_structure'] then link_to "Edit Practices", practices_path, :class => "btn btn-large btn-success pull-right practice-btn" end %>

<h1>Users</h1>
<table id="patientTable" class="table table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
      <% if APP_CONFIG['use_opml_structure'] %>
      <th>Provider</th>
      <% else %>
      <th>Practice</th>
      <th>Provider</th>
      <% end %>
      <th>Administrator</th>
      <th>Staff Role</th>
      <th>Approved</th>
      <th>Status</th>
      <th colspan="2"/>
    </tr>
  </thead>
  <% @users.each do |user| -%>
  <tbody>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.username %></td>

    <% if APP_CONFIG['use_opml_structure'] %>
    <td>
      <select class="npi_select" data-username="<%= user.username %>" name="user[npi]">
        <option value="-1">&nbsp;</option>
        <% Provider.all.alphabetical.each do |provider| %>
          <option value="<%= provider.npi %>" <%= (user.npi == provider.npi) ? "selected=\"selected\"" : ""%>><%= provider.full_name %> </option>
        <% end%>
      </select>
    </td>
    <% else %>
      <td> 
        <% if Provider.valid_npi?(user.npi) %>
          N/A
        <% else %>
        <%= select_tag "practice", options_for_select(@practices, user.practice_id), prompt: 'None', data: {user: user.id.to_s}, class: 'practice_select'%> 
        <% end %>
      </td>
      

      <td> 
        <% if Provider.valid_npi?(user.npi) %>
        <% @practice_pvs = Provider.by_npi(user.npi).map {|pv| if pv.try(:parent).try(:practice) then [pv.parent.practice.name + " - " + pv.full_name, pv.id] end}%>
        <%= select_tag "practice_provider_select", options_for_select(@practice_pvs, user.provider_id), prompt: 'None', data: {user: user.id.to_s}, class: 'practice_provider_select'%> 
        <% else %>
          N/A
        <% end %>
      </td>

    <% end %>
    <td>
      <% if user.admin? -%>
      Yes - <a href="#" class="demote" data-role="admin" data-username="<%= user.username %>">revoke</a>
      <% else -%>
      No - <a href="#" class="promote" data-role="admin" data-username="<%= user.username %>">grant</a>
      <% end -%>
    </td>
    <td>
      <% if Provider.valid_npi?(user.npi) %>
        N/A
      <% else %>
        <% if user.staff_role? -%>
        Yes - <a href="#" class="demote" data-role="staff_role" data-username="<%= user.username %>">revoke</a>
        <% else -%>
        No - <a href="#" class="promote" data-role="staff_role" data-username="<%= user.username %>">grant</a>
        <% end -%>
      <% end %>
    </td>
    <td>
      <% if user.approved? -%>
      true
      <% else -%>
      <a href="#" class="approve" data-username="<%= user.username %>">approve</a>
      <% end -%>
    </td>
    <td>
      <a href="#" class="<%= (user.disabled?) ? 'disable' : 'enable'%>" data-username="<%= user.username %>"><%= (user.disabled?) ? 'disabled' : 'enabled'%></a>
    </td>
    <td>
      <%= link_to "View Info",{:controller => "admin", :action => "user_profile", :id => user._id}, :class => "btn btn-info"%>    
      <%= link_to "Delete User", {:controller => "admin", :action => "delete_user", :id => user._id}, 'method' => 'delete', 'class' => 'btn btn-danger delete-user-btn', data: {'confirm' => "Are you sure you want to delete this user?"} %>    			  
    </td>
  </tr>
  </tbody>
  <% end -%>
</table>
</div> <!-- pageContent -->