config/routes.rb
PopHealth::Application.routes.draw do

  apipie

  devise_for :users, :controllers => {:registrations => "registrations"}

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  get "admin/jobs"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  delete "admin/remove_jobs"
  post 'api/measures/finalize'
  post 'api/measures/update_metadata'
  get "logs/index"
  post 'home/set_reporting_period'
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default"
  get 'home/check_authorization'
  delete "practices/remove_patients"
  delete "practices/remove_providers"
  delete "/api/admin/patients/deletePatientsFromPractice"

  put 'admin/patient', :to => 'admin/patients#upload_single_patient'

  root :to => 'home#index'

  resources :practices

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    get :measure_baseline

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams

  namespace :api do
    get 'reports/*qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
    get 'reports/*cat1.zip', :to =>'reports#cat1_zip', :format => :zip
    get 'reports/cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/patients', :to => 'reports#patients'
    get 'reports/measures_spreadsheet', :to =>'reports#measures_spreadsheet'
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/team_report', :to => 'reports#team_report'

    get 'value_sets/:oid', :to => 'value_sets#show', :oid => /([^\/])+?/, :format => :json

    resources :practices do
      collection do
        get :search
      end
    end
    
    resources :measure_baselines
    resources :practices
    resources :teams
    namespace :admin do
      resource :caches do
        collection do
          get :count
          get :spinner
          get 'static_measure/:id', :to => :static_measure
        end
      end
      resource :patients do
        collection do
          get :count
        end
      end
      resource :providers do
        collection do
          get :count
        end
      end
      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
    resources :providers do
      collection do
        get :search
      end
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end
    end
    resources :patients do
      member do
        get :results
      end
    end

    resources :measures

    resources :queries do
       member do
        get :patients
        get :patient_results
        put :recalculate
        post :filter
        post :clearfilters
       end
    end
  end

end

app/views/shared/_fraction.html.erb
<span class="paren">(</span>
<div class="inline-fraction">
    <span class="numeratorValue"><%= numerator %></span>
    <span class="separator"></span>
    <span class="denominatorValue"><%= denominator %></span>
</div><span class="paren">)</span>

app/views/shared/_header.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header col-lg-4">
      <a class="logo"  href="/" style="max-width: initial"><%= image_tag "pophealth_logo_small-trans.png" %></a>
    </div>
    <div class="collapse navbar-collapse in">
      <ul class="nav navbar-nav pull-left" style="margin-top: 10px">
        <li class="location"><%# if Provider.root %><%#= Provider.root.given_name %><%# else %><%#= APP_CONFIG['practice_name'] %><%# end %>
          <%=
            if APP_CONFIG['use_opml_structure']
              if Provider.root
                Provider.root.given_name
              else
                APP_CONFIG['practice_name']
              end
            else
              current_user.practice ? current_user.practice.name : ''
            end
          %>
        </li>
      </ul>
       <ul class="nav pull-right">
        <li class="divider-vertical"></li>
        <li class="profile">
          <div class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="glyphicon glyphicon-user"></i>
              <%= current_user.first_name.to_s %>
            </a>
            <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="User">
              <% if APP_CONFIG['edit_account_enabled']%>
                <li><%=link_to raw('<i class="glyphicon glyphicon-edit"></i> Edit Account'), edit_user_registration_path(current_user) %></li>
              <% end %>
              <% if APP_CONFIG['logout_enabled']%>
                <li><%= link_to raw('<i class="glyphicon glyphicon-log-out"></i> Logout'), destroy_user_session_path, method: 'delete' %></li>
              <% end %>
              <% if current_user.staff_role? || current_user.admin? %>
                <li class="divider"></li>
                <li role="presentation" class="dropdown-header">Admin</li>
                <% if current_user.admin? && !APP_CONFIG['use_opml_structure']%> 
                  <li><%= link_to raw('<i class="glyphicon glyphicon-th-large"></i> Practices'), practices_path %></li> 
                <% end %>
                <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Providers'), '/#providers'%></li>
                <li><%= link_to raw('<i class="glyphicon glyphicon-list"></i> Manage Teams'), '/teams'%></li>
                <% if current_user.admin? %>
                  <% if (APP_CONFIG['patient_management_enabled']) %>
                    <li><%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i> Patients'), admin_patients_path%></li>
                  <% end %>
                  <% if (APP_CONFIG['job_management_enabled']) %>
                    <li><%= link_to raw('<i class="fa fa-tasks"></i> Jobs'), admin_jobs_path%></li>
                  <% end %>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-user"></i> Users'), admin_users_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-list-alt"></i> Logs'), logs_index_path%></li>
                  <li><%= link_to raw('<i class="glyphicon glyphicon-plus"></i> Measures'), '/#admin/measures'%></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </li>
        <li class="divider-vertical"></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_measure_metrics.html.erb
<div id="measureMetrics">
  
  <div id="measurePopulationPercentage" class="span7">
    <%= image_tag "loading.gif", :id => "loadingAggregate", :style => "display:none;margin-top:12px" %>
    <h1><%= display_raw_percentage(numerator, denominator) %></h1>
  </div>
  <div style="text-align:center" class="span5">
    <%= render :partial => "shared/fraction", locals: {numerator: numerator, denominator: denominator}%>
  </div>
</div>

app/views/shared/_measure_title.html.erb
<div class="span10" id="measureDetailTitle">
  <%= content_for :export_links %>
  <dl class="dl-horizontal">
    <dt>Measure Name:</dt>
    <dd>      
      <%= measure['name']%>
      <% if measure['short_subtitle']%>
        - <%= measure['short_subtitle'] %>
      <% end %>
      <dt>Reporting Period:</dt>
      <dd>
        <span id="measurementPeriodStartDate"><%= Time.at(start_date).strftime("%m/%d/%Y") %> - <%= Time.at(effective_date).strftime("%m/%d/%Y") %></span>
      </dd>
      <dt>Description:</dt>
      <dd>
        <span id="measureDescText"><%= measure['description'] %></span>
      </dd>
    </dd>
  </dl>
</div><!-- end #measureDetailTable -->

app/views/shared/_table_bar.html.erb
<div class="tableBar">
  <div class="tableBarNumerator" style="width:<%= numerator_width(numerator, patient_count)%>"><span></span></div>
  <div class="tableBarDenominator" style="width:<%= denominator_width(numerator, denominator, patient_count)%>"><span></span></div>
  <div class="tableBarExclusion" style="width:<%= exclusion_width(exclusions, patient_count)%>"><span></span></div>
</div>

app/views/shared/_top_nav.html.erb
ß<div id="logOut">
  Welcome, <%= current_user.first_name.to_s %>
  <span class="sep">|</span> <a href="http://projectpophealth.org/faq.html">help</a>
  <% if APP_CONFIG['edit_account_enabled']%><span class="sep">|</span> <%= link_to 'account', edit_user_registration_path(current_user) %> <% end %>
  <% if current_user.staff_role? || current_user.admin? %> <span class="sep">|</span> <a id="manage_link" href="javascript:void(0)">manage</a> <% end %>
  <% if APP_CONFIG['logout_enabled']%><span class="sep">|</span> <%= link_to 'logout', destroy_user_session_path, 'class' => 'log'%> <% end %>
  
  <ul id="manage-menu" class="ui-menu ui-widget ui-widget-content ui-corner-all dialog-menu" role="listbox" aria-activedescendant="ui-active-menuitem">
    <% if current_user.staff_role? || current_user.admin? %>
    <li class="ui-menu-item" role="menuitem" data-type="providers">
      <a class="ui-corner-all" tabindex="-1" href="<%=providers_path%>">Providers</a>
    </li>
    <% end %>
    <% if current_user.admin? %>
      <li class="ui-menu-item" role="menuitem" data-type="users">
        <a class="ui-corner-all" tabindex="-1" href="<%=admin_users_path%>">Users</a>
      </li>
      
      <% if (APP_CONFIG['patient_management_enabled']) %>
      <li class="ui-menu-item" role="menuitem" data-type="patients">
        <a class="ui-corner-all" tabindex="-1" href="<%=admin_patients_path%>">Patients</a>
      </li>
      <% end %>

      <li class="ui-menu-item" role="menuitem" data-type="logs">
        <a class="ui-corner-all" tabindex="-1" href="<%= logs_index_path%>">Logs</a>
      </li>
    <% end %>
    
  </ul>
  
  <script type="text/javascript">
    var popHealth = popHealth || {};
  
    $(document).ready(function() {
      $('#manage_link').hover(popHealth.manageMenuIn, popHealth.manageMenuOut)
      $('#manage_link').mousemove(popHealth.manageMenuIn)
      $('.dialog-menu li a').hover(function() { $(this).addClass('ui-state-hover') } , function() { $(this).removeClass('ui-state-hover')} )
    });
    
    popHealth.manageMenuOut = function(data) {
    }
    popHealth.manageMenuIn = function(data) {
      position = $(this).offset()
      dialog = $( "#manage-menu" ).dialog({ position: [position.left - 2, (position.top + $(this).height() - $(window).scrollTop())], resizable: false, dialogClass: 'dialog-menuwindow', minWidth: false, minHeight: false, width: 100 }).css('padding', '2px');
      dialog.hover(popHealth.manageDialogHoverIn, popHealth.manageDialogHoverOut )
      $(this).hover(function() {}, popHealth.manageMenuHoverOut)
    }
    popHealth.manageMenuHasMouse=false;
    popHealth.manageDialogHoverIn = function() {
      popHealth.manageMenuHasMouse=true
    }
    popHealth.manageDialogHoverOut = function() {
      popHealth.manageMenuHasMouse=false;
      popHealth.closeDialog();
    }
    popHealth.closeDialog = function() {
      if (!popHealth.manageMenuHasMouse) {
        dialog.dialog('close'); 
        popHealth.manageMenuHasMouse=false;
      } else {
        setTimeout(popHealth.closeDialog, 600);
      }
    }
    
    popHealth.manageMenuHoverOut = function() {
      setTimeout(popHealth.closeDialog, 600) 
    }
    
    
  </script>
  
</div>