config/routes.rb
PopHealth::Application.routes.draw do

  apipie

  devise_for :users, :controllers => {:registrations => "registrations"}

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  post "admin/update_npi"
  get "admin/patients"
  get "admin/jobs"
  put "admin/upload_patients"
  put "admin/upload_providers"
  delete "admin/remove_patients"
  delete "admin/remove_caches"
  delete "admin/remove_providers"
  delete "admin/remove_jobs"
  post 'api/measures/finalize'
  post 'api/measures/update_metadata'
  get "logs/index"
  post 'home/set_reporting_period'
  get "admin/user_profile"
  delete "admin/delete_user"
  post 'admin/set_user_practice'
  post 'admin/set_user_practice_provider'
  post "teams/:id/update", :to => 'teams#update'
  post "teams/create"
  post "teams/create_default"
  get 'home/check_authorization'
  delete "practices/remove_patients"
  delete "practices/remove_providers"
  delete "/api/admin/patients/deletePatientsFromPractice"

  put 'admin/patient', :to => 'admin/patients#upload_single_patient'

  root :to => 'home#index'

  resources :practices

  resources :providers do
    resources :patients do
      collection do
        get :manage
        put :update_all
      end
    end

    get :measure_baseline

    member do
      get :merge_list
      put :merge
    end
  end

  resources :teams

  namespace :api do
    get 'reports/*qrda_cat3.xml', :to =>'reports#cat3', :format => :xml
    get 'reports/*cat1.zip', :to =>'reports#cat1_zip', :format => :zip
    get 'reports/cat1/:id/:measure_ids', :to =>'reports#cat1', :format => :xml
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/patients', :to => 'reports#patients'
    get 'reports/measures_spreadsheet', :to =>'reports#measures_spreadsheet'
    get 'teams/team_providers/:id', :to => 'teams#team_providers'
    get 'reports/team_report', :to => 'reports#team_report'

    get 'value_sets/:oid', :to => 'value_sets#show', :oid => /([^\/])+?/, :format => :json

    resources :practices do
      collection do
        get :search
      end
    end
    
    resources :measure_baselines
    resources :practices
    resources :teams
    namespace :admin do
      resource :caches do
        collection do
          get :count
          get :spinner
          get 'static_measure/:id', :to => :static_measure
        end
      end
      resource :patients do
        collection do
          get :count
        end
      end
      resource :providers do
        collection do
          get :count
        end
      end
      resources :users do
        member do
          get :enable
          get :disable
          post :promote
          post :demote
          get :approve
          get :update_npi
        end
      end
    end
    resources :providers do
      collection do
        get :search
      end
      resources :patients do
        collection do
          get :manage
          put :update_all
        end
      end
    end
    resources :patients do
      member do
        get :results
      end
    end

    resources :measures

    resources :queries do
       member do
        get :patients
        get :patient_results
        put :recalculate
        post :filter
        post :clearfilters
       end
    end
  end

end

app/models/practice.rb
class Practice
  include Mongoid::Document

  field :name, type: String
  field :organization, type: String
  field :address, type: String
  field :provider_id, type: BSON::ObjectId
  
  validates_presence_of :name, :organization
  validates :name, uniqueness: true
  belongs_to :provider, dependent: :destroy
  has_many :users
  has_many :records
  
  def providers
    Provider.all({"parent_ids" => self.provider_id })
  end

end

app/controllers/api/practices_controller.rb
module Api
  class PracticesController < ApplicationController
    resource_description do
      resource_id 'Admin::Practices'
      short 'Practices'
      formats ['json']
      description "This resource allows for the management of practices/organizations in the popHealth application."
    end
    include LogsHelper
    before_filter :authenticate_user!
    before_filter :validate_authorization!
    skip_before_action :verify_authenticity_token

    api :GET, "/practices/:id", "Get the practice information"
    formats ['json']
    def show
      log_api_call LogAction::VIEW, "View practice"
      practice = Practice.find(params[:id])
      render :json => practice.as_json
    end
    
    api :GET, "/practices", "Get all practice information"
    formats ['json']
    def index
      log_api_call LogAction::VIEW, "View all practices"
      practices = Practice.all
      render :json => practices.as_json
    end  
    
    api :POST, "/practices", "Create a practice"
    param :name, String, :desc => "Practice Name", :required => true
    param :organization, String, :desc => "Practice organization", :required => true
    param :user, String, :desc => "User to assign to practice (UserID)", :required => false
    param :address, String, :desc => "Address",  :required => false
    formats ['json']
    def create
      @practice = Practice.create(:name => params[:name], :organization => params[:organization], :address => params[:address])

      if @practice.save!
        identifier = CDAIdentifier.new(:root => "Organization", :extension => @practice.organization)
        provider = Provider.new(:given_name => @practice.name)
        provider.cda_identifiers << identifier
        # provider.parent = Provider.root  # was this just cut and paste from providers?
        provider.save
        @practice.provider = provider
        
        if params[:user] != '' && params[:user]
          user = User.find(params[:user])
          @practice.users << user
          user.save
        end
        @practice.save!
        log_api_call LogAction::ADD, "Created practice"
      else
        log_api_call LogAction::ADD, "Failed to create practice, with errors #{get_errors_for_log(@practice)}"
        @practice = nil
      end
      render :json => @practice
    end
    
    api :GET, "/practices/search?tin=:tin&address=:address", "Search for practice by a full or partial TIN"
    param :tin, String, :desc => "Tax Identification Number", :required => false
    param :address, String, :desc => "Provider/Practice Address", :required => false
    def search
      if !params[:tin].blank?
        practices = Provider.all({"cda_identifiers.root" => "2.16.840.1.113883.4.2", "cda_identifiers.extension" => /.*#{params[:tin]}.*/i })
        render json: practices.map {|p| { id: p.practice.id, name: "#{p.full_name} (#{p.tin})"} }
      elsif !params[:address].blank?
        practices = Practice.all({"address" => /.*#{params[:address]}.*/i })
        render json: practices.map { |p| { id: p.id, name: p.address } }
      else
        render :nothing => true, :status => 400
      end
    end


    private 

    def validate_authorization!
      authorize! :admin, :practices
      authorize! :admin, :providers
    end
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  include LogsHelper

  authorize_resource
  before_filter :authenticate_user!  
 	before_filter :validate_authorization

  # GET /practice
  # GET /practice.json
  
  def validate_authorization
  	authorize! :admin, :practice
  end
  
  def index
    log_controller_call LogAction::VIEW, "View all practices"
    @practices = Practice.all
		@practice = Practice.new
		@users = User.all.map {|user| [user.username, user.id]}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @practice }
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    log_controller_call LogAction::VIEW, "View practice"
    @practice = Practice.find(params[:id])
    @users = User.all.map {|user| [user.username, user.id]}
    if @practice.nil?
      respond_to do |format|
        format.html { redirect_to practices_path, notice: 'A practice with that identifier could not be found.' }
        format.json { render json: @practice, status: :not_found }
      end
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @practice }
      end
    end
  end
  
  # POST /practices
  # POST /practices.json
  def create
    log_controller_call LogAction::ADD, "Create practice"
    @practice = Practice.new(params[:practice])

    if @practice.save
      identifier = CDAIdentifier.new(:root => "Organization", :extension => @practice.organization)
      provider = Provider.new(:given_name => @practice.name)
      provider.cda_identifiers << identifier
      # provider.parent = Provider.root
      provider.save
      @practice.provider = provider
      
      if params[:user] != ''
        user = User.find(params[:user])
        @practice.users << user
        user.save
      end
    end
   
    respond_to do |format|
      if @practice.save
        format.html { redirect_to practices_path, notice: 'Practice was successfully created.' }
        format.json { render json: @practice, status: :created, location: @practice }
      else
        format.html { redirect_to practices_path }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /practices
  # PUT /practices.json
  def update
    @practice = Practice.find(params[:id])
    @practice.update_attributes(params[:practice]) unless @practice.nil?

    respond_to do |format|
      if @practice.save
        log_controller_call LogAction::UPDATE, "Update practice"
        format.html { redirect_to practices_path, notice: 'Practice was successfully updated.' }
        format.json { render json: @practice, status: :created, location: @practice }
      else
        log_controller_call LogAction::UPDATE, "Failed to update practice, with errors #{get_errors_for_log(@practice)}"
        format.html { redirect_to practices_path }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def remove_patients
    log_controller_call LogAction::DELETE, "Remove all patients for practice", true
    Record.where(practice_id: params[:id]).delete
    respond_to do |format|
      format.html { redirect_to :action => :index }
    end
  end
  
  def remove_providers
    log_controller_call LogAction::DELETE, "Remove all providers for practice"
    practice = Practice.find(params[:id])
    Provider.where(parent_id: practice.provider.id).delete
    
    respond_to do |format|
      format.html { redirect_to :action => :index }
    end
  end
  
  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    log_controller_call LogAction::DELETE, "Remove practice"
    @practice = Practice.find(params[:id])
    Record.where(practice_id: @practice.id).delete
    if @practice.provider
      id = @practice.provider.id
      @current_user.teams.each do |tm|
        team.providers.delete(id.to_s)
        team.save!
      end
      @current_user.save!
      @practice.provider.delete
    end
    @practice.destroy

    respond_to do |format|
      format.html { redirect_to :action => :index}
    end
  end
end

app/views/practices/_edit_practice.html.erb
<div class='form-inline'>
<%= form_for @practice do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>
      <ul>
      <% @practice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4> <%= @practice.new_record? ? "Create" : "Edit" %> Practice </h4>
  <table class="table-condensed table-hover">
    <tbody>
      <tr>
        <td><%= f.label :name, "*Name" %></td>
        <td><%= f.text_field :name %></td>        
      </tr>
      <tr>
        <td><%= f.label :organization, "*Organization" %></td>
        <td><%= f.text_field :organization %></td>        
      </tr>
      <tr>
        <td><%= f.label :address %></td>
        <td><%= f.text_area :address %></td>        
      </tr>
      <% if @practice.new_record? %>
      <tr>
        <td><%= f.label :user, "User" %></td>
        <td><%= select_tag :user, options_for_select(@users), include_blank: true %></td>        
      </tr>
      <% end %>
      <tr class='pull-right'> <td><%= f.submit class: "btn new-practice-btn"%></td> </tr>
    </tbody>
  </table>

<% end %>
</div>

app/views/practices/index.html.erb
<div class="practices">
  <h1>Practices</h1>
  <br/>  
  <%= render 'edit_practice' %>
	<br />
	<h4> Current Practices </h4>
	<table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Organization</th>
        <th>Address</th>
        <th>User(s)</th>
        <th>Patients</th>
        <th>Providers</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
  <% @practices.each do |practice| %>
    <tbody>
      <tr>
        <td><%= practice.name %></td>
        <td><%= practice.organization %></td>
        <td><%= practice.address %></td> 
        <td><%= practice.users ? practice.users.map {|u| u.username}.join(", ") : 'N/A' %></td>                
        <td><%= practice.records ? practice.records.count : 0 %></td>
        <td><%= practice.provider ? practice.provider.descendants.count : 'N/A'%></td>
        <td><%= link_to "Edit Practice", practice_path(practice.id), :class => "btn btn-primary" %></td>
        <td><%= link_to "Delete Providers", practices_remove_providers_path(id: practice.id), method: :delete, data: { confirm: 'Are you sure you want to delete all providers for ' + "#{practice.name}?"} %></td>
        <td><%= link_to "Delete Patients", practices_remove_patients_path(id: practice.id), method: :delete, data: { confirm: 'Are you sure you want to delete all patients for ' + "#{practice.name}?"} %></td>
        <td><%= link_to 'Delete Practice', practice, method: :delete, data: { confirm: 'Are you sure? There may be patients tied to this practice' } %></td>
      </tr>
    </tbody>
  <% end %>
  </table>
	<br />
  <%= link_to 'Back to Users', "/admin/users", class: 'btn btn-success' %>
  <%= link_to 'Back to Patients', "/admin/patients", class: 'btn btn-info' %>
</div>

app/views/practices/show.html.erb
<div class="practices">
  <h1>Practices</h1>
  <br/>  
  <%= render 'edit_practice' %>
  <br />
  <%= link_to 'Back to Practices', practices_path, class: 'btn btn-success' %>
</div>